{
  "title": "Brewfather",
  "config": {
    "step": {
      "user": {
        "title": "Detalhes da Conexão",
        "description": "Para conectar ao Brewfather você precia preencher todos os dados abaixo. Certifique-se que a API-Key tenha acesso aos escopos corretos",
        "data": {
          "name": "Nome da Conexão",
          "username": "ID de usuário",
          "password": "API-Key",
          "ramp_temp_correction": "Enable temperature ramping",
          "multi_batch": "Multiple batch support (preview)"
        }
      }
    },
    "error": {
      "cannot_connect": "Falha no registro, por favor tente novamente.",
      "invalid_scope": "A API-Key não tem acesso aos escopos corretos",
      "invalid_api_key": "Não foi possível autenticar com as credenciais fornecidas",
      "unknown": "Algo errado aconteceu"
    },
    "abort": {
      "already_configured": "API-Key já configurada"
    }
  },
  "options": {
    "step": {
      "init": {
        "data": {
          "ramp_temp_correction": "Enable temperature ramping",
          "multi_batch": "Multiple batch support (preview)",
          "all_batch_info_sensor": "All batches data sensor (experimental)",
          "custom_stream_enabled": "Enable custom stream"
        }
      },
      "custom_stream": {
        "data": {
          "custom_stream_logging_id": "BrewFathers logging-id",
          "custom_stream_temperature_entity_name": "Full entity name for temperature",
          "custom_stream_temperature_entity_attribute": "Attribute name of the temperature entity"
        }
      }
    },
    "error": {
      "invalid_logging_id": "Logging-id seems invalid, please check BrewFather App docs for \"Custom Stream\"",
      "entity_not_found": "Unable to find entity with given name",
      "attribute_not_found": "Unable to find attribute with given name",
      "unknown": "Algo errado aconteceu"
    }
  }
}
